(**
   Includes all modules neccessary for using preferences stuff.
**)

MODULE VO:Prefs:All;

(*
    Includes all modules neccessary for using preferences stuff.
    Copyright (C) 1997  Tim Teulings (rael@edge.ping.de)

    This module is free software; you can redistribute it and/or
    modify it under the terms of the GNU Lesser General Public License
    as published by the Free Software Foundation; either version 2 of
    the License, or (at your option) any later version.

    This module is distributed in the hope that it will be useful, but
    WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
    Lesser General Public License for more details.

    You should have received a copy of the GNU Lesser General Public
    License along with VisualOberon. If not, write to the Free Software Foundation,
    59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
*)

<* PUSH; Warnings:=FALSE *>

IMPORT VO:Prefs:Array,
       VO:Prefs:Bool,
       VO:Prefs:Button,
       VO:Prefs:ButtonRow,
       VO:Prefs:Clock,
       VO:Prefs:Combo,
       VO:Prefs:Date,
       VO:Prefs:DigiClock,
       VO:Prefs:Display,
       VO:Prefs:FrameGroup,
       VO:Prefs:FuelGauge,
       VO:Prefs:Grid,
       VO:Prefs:Header,
       VO:Prefs:Knob,
       VO:Prefs:Label,
       VO:Prefs:LED,
       VO:Prefs:LightChain,
       VO:Prefs:Load,
       VO:Prefs:Menu,
       VO:Prefs:Multi,
       VO:Prefs:Object,
       VO:Prefs:Oszil,
       VO:Prefs:Panel,
       VO:Prefs:PatternLegend,
       VO:Prefs:PieChart,
       VO:Prefs:Plate,
       VO:Prefs:Power,
       VO:Prefs:QuickHelp,
       VO:Prefs:Radio,
       VO:Prefs:Scale,
       VO:Prefs:Scroller,
       VO:Prefs:Slider,
       VO:Prefs:Space,
       VO:Prefs:StatusLine,
       VO:Prefs:String,
       VO:Prefs:StringClock,
       VO:Prefs:Tab,
       VO:Prefs:Table,
       VO:Prefs:TableView,
       VO:Prefs:Text,
       VO:Prefs:Toolbar,
       VO:Prefs:Tree,
       VO:Prefs:ViewOneOfN,
       VO:Prefs:Window,
       VO:Prefs:WindowGroup;

END VO:Prefs:All.

<* POP *>
